name: Release (MacOS)

on:
  workflow_call:
    inputs:
      discord_game_sdk_version:
        required: true
        type: string

jobs:
  macos:
    name: MacOS

    runs-on: macos-12
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13

    steps:
    - name: Download source
      uses: actions/download-artifact@v3
      with:
        name: internal-source

    - name: Unpack source
      run: |
        tar -xf source.tar.gz --strip-components=1

    - name: Install Discord SDK
      shell: bash
      run: |
        ./download-sdk.sh ${{ inputs.discord_game_sdk_version }}

    - name: Install GCC problem matcher
      uses: ammaraskar/gcc-problem-matcher@master

    - name: Build arm64
      run: |
        mkdir build-arm64
        cd build-arm64

        echo "::group::CMake"
        cmake ${GITHUB_WORKSPACE} \
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          # EOF
        echo "::endgroup::"

        echo "::group::Build"
        echo "Running on $(sysctl -n hw.logicalcpu) cores"
        cmake --build . -j $(sysctl -n hw.logicalcpu)
        echo "::endgroup::"

    - name: Build x64
      run: |
        mkdir build-x64
        cd build-x64

        echo "::group::CMake"
        cmake ${GITHUB_WORKSPACE} \
          -DCMAKE_OSX_ARCHITECTURES=x86_64 \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          # EOF
        echo "::endgroup::"

        echo "::group::Build"
        echo "Running on $(sysctl -n hw.logicalcpu) cores"
        cmake --build . -j $(sysctl -n hw.logicalcpu)
        echo "::endgroup::"

    - name: Create bundles
      run: |
        cd build-x64

        echo "::group::Create universal binary"
        find ../build-*
        # Combine the binaries from each build into a single file
        lipo -create -output libdiscord-social-universl.dylib ../build-*/libdiscord-social.dylib
        mv libdiscord-social-universal.dylib libdiscord-social.dylib
        echo "::endgroup::"

        echo "::group::Run install"
        make install
        echo "::endgroup::"

        echo "::group::Create bundle"
        mkdir -p bundles
        (
            cd install/lib
            zip -r ../../bundles/discord-social-macos-universal.zip .
        )
        echo "::endgroup::"

    - name: Store bundles
      uses: actions/upload-artifact@v3
      with:
        name: openttd-macos-universal
        path: build-x64/bundles
        retention-days: 5
