name: Release (Windows)

on:
  workflow_call:

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: x86
          host: x86
        - arch: x64
          host: x64

    name: Windows (${{ matrix.arch }})

    runs-on: windows-latest

    steps:
    - name: Download source
      uses: actions/download-artifact@v3
      with:
        name: internal-source

    - name: Unpack source
      shell: bash
      run: |
        tar -xf source.tar.gz --strip-components=1

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Enable Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Install breakpad dependencies"
        cargo install dump_syms
        echo "::endgroup::"

    - name: Install Discord SDK
      shell: bash
      run: |
        ./download-sdk.sh ${{ vars.DISCORD_GAME_SDK_VERSION }}

    - name: Install MSVC problem matcher
      uses: ammaraskar/msvc-problem-matcher@master

    - name: Configure developer command prompt for ${{ matrix.arch }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.host }}

    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build

        echo "::group::CMake"
        cmake ${GITHUB_WORKSPACE} \
          -GNinja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          # EOF
        echo "::endgroup::"

        echo "::group::Build"
        cmake --build .
        echo "::endgroup::"

    - name: Create breakpad symbols
      shell: bash
      run: |
        cd build
        dump_syms discord-social.pdb --inlines --store symbols

    - name: Create bundles
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/build
        echo "::group::Run CPack"
        cpack
        echo "::endgroup::"

        echo "::group::Move PDB and dll to symbols"
        PDB_FOLDER=$(find symbols -mindepth 2 -type d)
        cp discord-social.pdb ${PDB_FOLDER}/

        EXE_FOLDER=symbols/discord-social.dll/$(grep "INFO CODE_ID" symbols/*/*/discord-social.sym | cut -d\  -f3)
        mkdir -p ${EXE_FOLDER}
        cp discord-social.dll ${EXE_FOLDER}/
        echo "::endgroup::"

    - name: Store bundles
      uses: actions/upload-artifact@v3
      with:
        name: discord-social-windows-${{ matrix.arch }}
        path: build/bundles
        retention-days: 5

    - name: Store symbols
      uses: actions/upload-artifact@v3
      with:
        name: symbols-windows-${{ matrix.arch }}
        path: build/symbols
        retention-days: 5
